const USER_STATUS = {
  'USER_CREATED': 'U-C-200',
  'USER_NONE_EMAIL': 'U-N-400',
  'USER_DUPLICATE_EMAIL': 'U-D-400',
  'USER_MISMATCH_PASSWORD': 'U-M-400',
  'USER_LOGIN_SUCCESS': 'U-L-200',
};

const TRANS_STATUS = {
  'TRANSACTION_GET_SUCCESS': 'T-G-200',
};

const CATEGORY_STATUS = {
  'CATEGORY_ALL_GET_SUCCESS': 'C-A-200',
};
